# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network :forwarded_port, guest: 8081, host: 8081
  config.vm.network "private_network", ip: "192.168.55.100"
  config.vm.hostname = "Auth"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Auth"
    vb.cpus = 2
    vb.memory = 2048
   end
   
  config.vm.provision "shell", path: 'initial_programs.sh'
end