# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network :forwarded_port, guest: 8082, host: 8082
  config.vm.network "private_network", ip: "192.168.55.4"
  config.vm.hostname = "TODOs"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "TODOs"
    vb.cpus = 2
    vb.memory = 2048
   end
 
   config.vm.provision "shell", path: 'initial_programs.sh'
end