# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  config.vm.network "private_network", ip: "192.168.55.5"
  config.vm.hostname = "Redis"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Redis"
    vb.cpus = 2
    vb.memory = 2048
   end
   
    config.vm.provision "shell", path: 'initial_programs.sh'
end
